[package]
name = "pregonero"
version = "0.1.0"
authors = ["Dario Blanco Iturriaga"]
edition = "2021"

[dependencies]
imap-proto = "0.16.2"
redis = { version = "0.23", features = ["aio", "tokio-comp"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[lib]
name = "pregonero"
path = "src/main.rs"
